<?php
abstract class HTTPResponseCode {
	// Informational
	const INFO_CONTINUE = 100;
	const INFO_SWITCHING_PROTOCOLS = 101;
	const INFO_PROCESSING = 102;
	const INFO_EARLY_HINTS = 103;
	// Success
	const SUCCESS_OK = 200;
	const SUCCESS_CREATED = 201;
	const SUCCESS_ACCEPTED = 202;
	const SUCCESS_NON_AUTHORITATIVE_INFORMATION = 203;
	const SUCCESS_NO_CONTENT = 204;
	const SUCCESS_RESET_CONTENT = 205;
	const SUCCESS_PARTIAL_CONTENT = 206;
	const SUCCESS_MULTI_STATUS = 207;
	const SUCCESS_ALREADY_REPORTED = 208;
	const SUCCESS_IM_USED = 226;
	// Redirects
	const REDIRECT_MULTIPLE_CHOICES = 300;
	const REDIRECT_MOVED_PERMANENTLY = 301;
	const REDIRECT_FOUND = 302;
	const REDIRECT_SEE_OTHER = 303;
	const REDIRECT_NOT_MODIFIED = 304;
	const REDIRECT_USE_PROXY = 305;
	const REDIRECT_UNUSED = 306;
	const REDIRECT_TEMPORARY_REDIRECT = 307;
	const REDIRECT_PERMANENT_REDIRECT = 308;
	// Client Errors
	const CLIENT_ERROR_BAD_REQUEST = 400;
	const CLIENT_ERROR_UNAUTHORIZED = 401;
	const CLIENT_ERROR_PAYMENT_REQUIRED = 402;
	const CLIENT_ERROR_FORBIDDEN = 403;
	const CLIENT_ERROR_NOT_FOUND = 404;
	const CLIENT_ERROR_METHOD_NOT_ALLOWED = 405;
	const CLIENT_ERROR_NOT_ACCEPTABLE = 406;
	const CLIENT_ERROR_PROXY_AUTHENTICATION_REQUIRED = 407;
	const CLIENT_ERROR_REQUEST_TIMEOUT = 408;
	const CLIENT_ERROR_CONFLICT = 409;
	const CLIENT_ERROR_GONE = 410;
	const CLIENT_ERROR_LENGTH_REQUIRED = 411;
	const CLIENT_ERROR_PRECONDITION_FAILED = 412;
	const CLIENT_ERROR_PAYLOAD_TOO_LARGE = 413;
	const CLIENT_ERROR_URI_TOO_LONG = 414;
	const CLIENT_ERROR_UNSUPPORTED_MEDIA_TYPE = 415;
	const CLIENT_ERROR_RANGE_NOT_SATISFIABLE = 416;
	const CLIENT_ERROR_EXPECTATION_FAILED = 417;
	const CLIENT_ERROR_IM_A_TEAPOT = 418;
	const CLIENT_ERROR_MISDIRECTED_REQUEST = 421;
	const CLIENT_ERROR_UNPROCESSABLE_ENTITY = 422;
	const CLIENT_ERROR_LOCKED = 423;
	const CLIENT_ERROR_FAILED_DEPENDENCY = 424;
	const CLIENT_ERROR_TOO_EARLY = 425;
	const CLIENT_ERROR_UPGRADE_REQUIRED = 426;
	const CLIENT_ERROR_PRECONDITION_REQUIRED = 428;
	const CLIENT_ERROR_TOO_MANY_REQUESTS = 429;
	const CLIENT_ERROR_REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
	const CLIENT_ERROR_UNAVAILABLE_FOR_LEGAL_REASONS = 451;
	// Server Errors
	const SERVER_ERROR_INTERNAL_SERVER_ERROR = 500;
	const SERVER_ERROR_NOT_IMPLEMENTED = 501;
	const SERVER_ERROR_BAD_GATEWAY = 502;
	const SERVER_ERROR_SERVICE_UNAVAILABLE = 503;
	const SERVER_ERROR_GATEWAY_TIMEOUT = 504;
	const SERVER_ERROR_HTTP_VERSION_NOT_SUPPORTED = 505;
	const SERVER_ERROR_VARIANT_ALSO_NEGOTIATES = 506;
	const SERVER_ERROR_INSUFFICIENT_STORAGE = 507;
	const SERVER_ERROR_LOOP_DETECTED = 508;
	const SERVER_ERROR_NOT_EXTENDED = 510;
	const SERVER_ERROR_NETWORK_AUTHENTICATION_REQUIRED = 511;
}
